# 264. Ugly Number II

class Solution:
    def nthUglyNumber(self, n):
        """
        :type n: int
        :rtype: int
        """

        step =  2
        result = []
        result.append(1)
        count = 1
        while True:
            if count == n:
                return result[-1]

            if self.util(step):
                result.append(step)
                count += 1

            step += 1

    def util(self, x):

        while x % 2 == 0:
            x = x / 2

        while x % 3 == 0:
            x = x / 3

        while x % 5 == 0:
            x = x / 5

        if x == 1:
            return True
        else:
            return False

'''
This generates the first n ugly numbers, in order from smallest to largest, in O(n) time. 
For each prime 2, 3 and 5, have an index to the next number that can be multiplied with the prime to produce a new ugly number. 
Update the three indexes and then add the smallest of the three candidate ugly numbers.

1. Use the existing ugly number to generate new ones by multiply 2, 3 or 5.
2. There are three lines of candidates, one for 2, one for 3 and the last for 5.
3. Always pick the smallest one and update for the next candidate for all the three candidate lines. 
'''

def nthUglyNumber(n):
    ugly = [1]

    # Use the first ugly number to generate the next possible.
    i2 = i3 = i5 = 0

    while len(ugly) < n:
        # Use existing ugly numbers to generate new ones by multiply 2 until a new large enough one is generated.
        while ugly[i2] * 2 <= ugly[-1]: i2 += 1
 
        # Another candidate. 
        # i3 is another line of queue.
        while ugly[i3] * 3 <= ugly[-1]: i3 += 1

        # The third candidate:
        while ugly[i5] * 5 <= ugly[-1]: i5 += 1
        ugly.append(min(ugly[i2] * 2, ugly[i3] * 3, ugly[i5] * 5))

    return ugly[-1]

#######################################################################################################################################
# 313. Super Ugly Number

'''
Write a program to find the nth super ugly number.

Super ugly numbers are positive numbers whose all prime factors are in the given prime list primes of size k.

Input: n = 12, primes = [2,7,13,19]
Output: 32 
Explanation: [1,2,4,7,8,13,14,16,19,26,28,32] is the sequence of the first 12 
             super ugly numbers given primes = [2,7,13,19] of size 4.
'''

class Solution(object):

    # A candidate queue for each of the primes
    # Candidate queue is generated by the already added ugly number 
    def nthSuperUglyNumber(self, n, primes):
        """
        :type n: int
        :type primes: List[int]
        :rtype: int
        """

        result = [1]
        count = 1

        candidates = [0 for i in range(len(primes))]

        while count < n:

            # Generate candidates for each prime.
            for i in range(len(primes)):
                while result[candidates[i]] * primes[i] <= result[-1]:
                    candidates[i] += 1

            toselect = [result[candidates[i]] * primes[i] for i in range(len(primes))]
            a = min(toselect)
            result.append(a)
            count += 1

        return result[-1]
